FROM redhat/ubi8:latest

RUN yum install java -y
RUN java -version

RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz .
#RUN curl -O https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz
RUN tar -xvf apache-tomcat-8.5.85.tar.gz
RUN mv apache-tomcat-8.5.85 tomcat8
RUN rm -rf apache-tomcat*
RUN ls

EXPOSE 8080
CMD ["/opt/tomcat/tomcat8/bin/catalina.sh", "run"]
